# Generated by Django 4.1.1 on 2022-09-08 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='checkout_time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
